Opted for manual install script

diff --git a/.github/workflows/ci-deploy.yml b/.github/workflows/ci-deploy.yml
--- a/.github/workflows/ci-deploy.yml
+++ b/.github/workflows/ci-deploy.yml
@@ -15,7 +15,16 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
+        run: |
+          if ! docker buildx version &> /dev/null; then
+            echo "Docker Buildx not found. Installing..."
+            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
+            docker build --platform=local -o . git://github.com/docker/buildx
+            mkdir -p ~/.docker/cli-plugins
+            mv buildx ~/.docker/cli-plugins/docker-buildx
+          fi
+          docker buildx version
+        shell: bash
 
       - name: Login to Azure Container Registry
         uses: azure/docker-login@v1
